### ISSUE TITLE
Is it possible to programm a new Layout like NEO 2.0?

### ISSUE THREAD

**Issue by Tachiguro** [dietsche/kinesis-advantage-2#4]
I buyed a Kinesis Advantage2. But i use normal NEO 2.0 https://www.neo-layout.org/
is it possible to programm complete NEO 2.0 to Advantage?
Already programm al letters but not the other sighn... Dont know how to do this...

**Comment by farmergreg** [comment]
Hi @Tachiguro, I am not able to speak German so I can not help you. But maybe someone else can. Please submit a pull request with the neo layout to this repository. Then if someone knows how to help they can add to your layout.

**Comment by ofloveandhate** [comment]
neo looks like a software installation...  so this may be *very* hard to achieve on a kinesis.
